# This file is named "travis.sample.yml".
# Rename it ".travis.yml".
# http://docs.travis-ci.com/user/build-configuration/

language: python

sudo: required

python:
    - "3.4"

before_install:
    - sudo apt-get update

install:
    - pip install --upgrade pip
    - pip install coverage
    - pip install numpy

before_script:
    - uname -a
    - printenv
    - pip3 --version
    - pip3 freeze
    - python3 --version
    - coverage3 --version
    - python3 -c "import numpy; print(numpy.__version__)"

script:
    - date
    - ls -al
    - touch Netflix.log
    - rm RunNetflix.out
    - rm TestNetflix.out
    - make netflix-tests
    - ls -al
    - make Netflix.html
    - ls -al
    - make test
    - ls -al
    - make check
